const CATS=["全部","升学","实验室","研究","求职","收藏"];let view="全部",query="",expanded=null,items=[];
const state=loadState();
function loadState(){try{return JSON.parse(localStorage.getItem("daily-update-private"))||{saved:[],notes:{}}}catch{return{saved:[],notes:{}}}}
function saveState(message="私人状态已保存"){localStorage.setItem("daily-update-private",JSON.stringify({...state,updatedAt:new Date().toISOString()}));document.querySelector("#save-status").textContent=message}
async function loadData(){const files=["data/curated.json","data/automated.json"];const results=await Promise.all(files.map(async f=>{try{const r=await fetch(f,{cache:"no-store"});return r.ok?(await r.json()).items||[]:[]}catch{return[]}}));items=results.flat().sort((a,b)=>(b.priority||0)-(a.priority||0)||(b.updated_at||"").localeCompare(a.updated_at||""));render()}
function esc(v=""){return String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]))}
function filtered(){return items.filter(x=>(view==="全部"||view==="收藏"?view!=="收藏"||state.saved.includes(x.id):x.category===view)&&[x.title,x.title_en,x.organization,x.location,x.summary,x.relevance,...(x.tags||[])].join(" ").toLowerCase().includes(query.toLowerCase()))}
function renderNav(){document.querySelector("#nav").innerHTML=CATS.map(c=>`<button data-view="${c}" class="${view===c?"active":""}"><span>${c==="全部"?"今日更新":c==="收藏"?"已收藏":c+"更新"}</span><b>${c==="收藏"?state.saved.length:c==="全部"?items.length:items.filter(x=>x.category===c).length}</b></button>`).join("");document.querySelectorAll("[data-view]").forEach(b=>b.onclick=()=>{view=b.dataset.view;render()})}
function card(x,i){const saved=state.saved.includes(x.id),open=expanded===x.id;return `<article><div class="index">${String(i+1).padStart(2,"0")}</div><div><div class="top"><div><div class="meta"><span class="cat ${x.priority>=90?"urgent":""}">${esc(x.category)}</span><span>${esc(x.organization)}</span><span>${esc(x.location)}</span>${x.verification_status!=="verified"?"<span>⚠ 待核验</span>":""}</div><h4>${esc(x.title)}</h4>${x.title_en?`<p class="title-en">${esc(x.title_en)}</p>`:""}</div><button class="bookmark ${saved?"saved":""}" data-save="${esc(x.id)}">${saved?"已收藏":"收藏"}</button></div><div class="details-grid"><div><h5>摘要</h5><p>${esc(x.summary)}</p>${open&&x.summary_en?`<p class="english">${esc(x.summary_en)}</p>`:""}</div><div><h5>与你的关联</h5><p>${esc(x.relevance)}</p></div></div><div class="foot"><div class="tags">${(x.tags||[]).map(t=>`<span>${esc(t)}</span>`).join("")}</div><div class="dates"><span>更新 ${esc(x.updated_at||x.published_at)}</span>${x.deadline?`<strong>截止 ${esc(x.deadline)}</strong>`:""}</div><button class="expand" data-expand="${esc(x.id)}">${open?"收起":"展开"}</button><a class="source" href="${esc(x.source_url)}" target="_blank" rel="noreferrer">原始来源 ↗</a></div>${open?`<div class="notes"><label>私人备注<textarea data-note="${esc(x.id)}" placeholder="记录申请准备、疑问或后续行动；仅保存在本地。">${esc(state.notes[x.id]||"")}</textarea></label></div>`:""}</div></article>`}
function render(){renderNav();const list=filtered();document.querySelector("#tabs").innerHTML=CATS.slice(0,5).map(c=>`<button data-tab="${c}" class="${view===c?"active":""}">${c}</button>`).join("");document.querySelectorAll("[data-tab]").forEach(b=>b.onclick=()=>{view=b.dataset.tab;render()});document.querySelector("#view-title").textContent=view==="全部"?"今日更新内容":view==="收藏"?"已收藏内容":view+"更新";document.querySelector("#count").textContent=`共 ${list.length} 条・按优先级排序`;document.querySelector("#feed").innerHTML=list.length?list.map(card).join(""):'<p class="empty">当前筛选条件下没有内容。</p>';document.querySelector("#total").textContent=items.length;document.querySelector("#urgent").textContent=items.filter(x=>x.priority>=90).length;document.querySelector("#verify").textContent=items.filter(x=>x.verification_status!=="verified").length;document.querySelectorAll("[data-save]").forEach(b=>b.onclick=()=>{const id=b.dataset.save;state.saved=state.saved.includes(id)?state.saved.filter(x=>x!==id):[...state.saved,id];saveState();render()});document.querySelectorAll("[data-expand]").forEach(b=>b.onclick=()=>{expanded=expanded===b.dataset.expand?null:b.dataset.expand;render()});document.querySelectorAll("[data-note]").forEach(t=>t.oninput=()=>{state.notes[t.dataset.note]=t.value;saveState()})}
document.querySelector("#search").oninput=e=>{query=e.target.value;render()};document.querySelector("#export").onclick=()=>{const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:"application/json"}));a.download="Daily-Update.private.json";a.click();URL.revokeObjectURL(a.href);saveState("私人数据备份已下载")};document.querySelector("#import").onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result);state.saved=x.saved||[];state.notes=x.notes||{};saveState("已载入本地私人数据");render()}catch{document.querySelector("#save-status").textContent="文件格式无法识别"}};r.readAsText(f)};
const now=new Date();document.querySelector("#today").textContent=new Intl.DateTimeFormat("zh-CN",{dateStyle:"full",timeZone:"Asia/Shanghai"}).format(now);document.querySelector("#updated").textContent="每天北京时间 08:00 左右更新";loadData();
